# Generated by Django 4.0.8 on 2025-10-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_summary_alter_course_summary_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
