# Generated by Django 4.0.8 on 2025-10-27 04:18

import course.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_upload_is_available_uploadvideo_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='module_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='module_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip', upload_to=course.models.upload_to_course_files, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])]),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', upload_to=course.models.upload_to_course_videos, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
    ]
