# Generated by Django 4.0.8 on 2025-10-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0004_alter_result_semester'),
        ('course', '0009_upload_module_number_uploadvideo_module_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.PositiveIntegerField()),
                ('material_type', models.CharField(choices=[('file', 'File'), ('video', 'Video')], max_length=10)),
                ('taken_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='result.takencourse')),
            ],
            options={
                'verbose_name': 'Student Material Progress',
                'verbose_name_plural': 'Student Material Progress',
                'unique_together': {('taken_course', 'material_id', 'material_type')},
            },
        ),
    ]
