name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      EMAIL_HOST: localhost
      EMAIL_PORT: 1025
      EMAIL_USE_TLS: false
      EMAIL_FROM_ADDRESS: "Dolphin One <admin@dolphin-one.com>"
      EMAIL_HOST_USER: admin@dolphin-one.com
      EMAIL_HOST_PASSWORD: Welcome@4124
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
